### ISSUE TITLE
Article 1 has mistake!!!

### ISSUE THREAD

**Issue by Panibrat** [Panibrat/BSA2017_JS_Hometask1_Git#1]
Please change city name in article! It happend in Kiev

**Comment by Panibrat** [comment]
Done

**Comment by volodymyr-kushnir** [comment]
@Panibrat good work! Keep it up!

**Comment by Panibrat** [comment]
I'm doing my best :) Thanks!

**Comment by volodymyr-kushnir** [comment]
See [**this**](https://github.com/volodymyr-kushnir/agenda/) for some hints, perhaps some could be useful.
